Module17_ModelsAndViews/Models/ErrorViewModel.cs
namespace Module17_ModelsAndViews.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Module17_ModelsAndViews/Models/User.cs
namespace Module17_ModelsAndViews.Models
{
    public class User
    {
        public string Name { get; set; }
        public string Age { get; set; }
        public string City { get; set; }
    }
}

Module17_ModelsAndViews/ViewModels/UserViewModel.cs
namespace Module17_ModelsAndViews.ViewModels
{
    public class UserViewModel
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public string Email { get; set; }
    }
}

Module17_ModelsAndViews/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Module17_ModelsAndViews.Models;
using Module17_ModelsAndViews.ViewModels;

namespace Module17_ModelsAndViews.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    private static readonly User[] Users = new[]
                                           {
                                               new User
                                               {
                                                   Name = "Sasha",
                                                   Age = "22",
                                                   City = "Minsk"
                                               },
                                               new User
                                               {
                                                   Name = "Ira",
                                                   Age = "25",
                                                   City = "Minsk"
                                               },
                                               new User
                                               {
                                                   Name = "Kolya",
                                                   Age = "32",
                                                   City = "Pinsk"
                                               }
                                           };
    
    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult DataTransportByViewData()
    {
        ViewData["Users"] = Users;
        return View();
    }

    public IActionResult DataTransportByViewBag()
    {
        ViewBag.Users = Users;
        return View();
    }

    public IActionResult DataTransportByModel()
    {
        return View(Users);
    }

    public IActionResult ViewWithSeparateLayout()
    {
        return View(Users);
    }

    //RABOTA S MODELS:
    public IActionResult GetUsers()
    {
        var users = new List<UserViewModel>()
        {
            new UserViewModel
            {
                Name = "Sasha",
                Age = 23,
                Email = "sasha@yandex.ru"
            },
            new UserViewModel
            {
                Name = "Dmitriy",
                Age = 21,
                Email = "DIMA@yandex.ru"
            },
            new UserViewModel
            {
                Name = "VOLODYA",
                Age = 23,
                Email = "SHOFERVOLODYA@yandex.ru"
            },
        };
         return View(users);

    }

    public IActionResult GetUser()
    {   
            var user = new UserViewModel
        {
            Name = "Sasha",
            Age = 23,
            Email = "sasha@yandex.ru"
        };
        return View(user);  
    }

    [HttpPost]
    public IActionResult GetUser(UserViewModel model)
    {
        return View(model);
    }
    
}

Module17_ModelsAndViews/SeparateComponents/ViewExampleViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Module17_ModelsAndViews.SeparateComponents;

public class ViewExampleViewComponent : ViewComponent
{
    private static readonly string[] TestData =
    {
        "one",
        "two",
        "three"
    };
    
    public IViewComponentResult Invoke()
    {
       // return View("ViewExample", TestData);
        return View(TestData); //тут дефолт выведется
    }
}

Module17_ModelsAndViews/ViewComponents/SimpleViewComponent.cs
namespace Module17_ModelsAndViews.ViewComponents;

public class SimpleViewComponent
{
    public string Invoke()
    {
        return (2 + 2).ToString();
       // return nameof(SimpleViewComponent);
    }
}

Module17_ModelsAndViews/Views/Home/Components/ViewExample/Default.cshtml
Default

Module17_ModelsAndViews/Views/Home/Components/ViewExample/ViewExample.cshtml
@model IEnumerable<string>

<ul>
    @foreach (var item in Model)
    {
        @: <li>@item</li>
    }
</ul>

Module17_ModelsAndViews/Views/Home/DataTransportByModel.cshtml
@model User[]
@{
    ViewBag.Title = "DataTransportByModel";
}

<ul>
    @foreach (var user in Model)
    {
        <li>@("Name: " + user.Name + " Age: " + user.Age + " City: " + user.City)</li>
    }
</ul>

Module17_ModelsAndViews/Views/Home/DataTransportByViewBag.cshtml
@{
    var users = ViewBag.Users as User[];
    ViewBag.Title = "DataTransportByViewBag";
}

<ul>
    @foreach (var user in users)
    {
        <li>@("Name: " + user.Name + " Age: " + user.Age + " City: " + user.City)</li>
    }
</ul>

Module17_ModelsAndViews/Views/Home/DataTransportByViewData.cshtml
@{
    var users = ViewData["Users"] as User[];
    ViewBag.Title = "DataTransportByViewData";
}

<ul>
    @foreach (var user in users)
    {
        <li>@("Name: " + user.Name + " Age: " + user.Age + " City: " + user.City)</li>
    }
</ul>

Module17_ModelsAndViews/Views/Home/GetUser.cshtml
@model UserViewModel

@Html.DisplayFor(user => user.Name)
@Html.TextBoxFor(q => q.Name)
@*@Html.CheckBoxFor(q => true)*@
 @*SOZDAEM FORMY CHEREZ BEGINFORM CLIENT-SERVER*@
@using(Html.BeginForm(FormMethod.Post)){
    @Html.TextBoxFor(q => q.Name)
    @Html.TextBoxFor(q => q.Age)
    @Html.TextBoxFor(q => q.Email)
    <button type="submit">Click</button>
}

Module17_ModelsAndViews/Views/Home/GetUsers.cshtml
@model List<UserViewModel>
<ul>
    <h2>
        USER LIST:
    </h2>
    @foreach (var user in Model)
    {
        <li>
           @* <p>@user.Name</p>
            <p> @user.Email</p>
            <p> @user.Age</p>*@
            @("Name: " + user.Name + " Email: " + user.Email + " Age: " + user.Age)
        </li>
    }
</ul>

Module17_ModelsAndViews/Views/Home/Index.cshtml
@model User[]

@{
    ViewBag.Title = "Home Page";
    // Layout = "_TestLayout";
    ViewBag.Partial = "Partial";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
@*PERVOE*@
@Html.Partial("_PartialView", "Fish")   @*(Если основное представление лежит в одной папке с главным представлением то достаточно названия)

в скобках название частичного представления которое хотим вызвать. fish это строка которая передалась в паршиалвью моделью) *@
@*@{Html.RenderPartial("_PartialView","Fish");} *@ @*работает быстрее паршиала. ОБОРАЧИВАТЬ В ФИГУРНЫЕ СКОБКИ!!!! ЛУЧШЕ ИСПОЛЬЗОВАТЬ ПАРШИАЛ
    РЕНДЕР ПАРШИАЛ ЮЗАЮТ ТОЛЬКО ТАМ ГДЕ НЕОБХОДИМО. 
*@

@*SECOND: ГЕНЕРАЦИЯ ССЫЬЛКИ НИЖЕ: генерируем ссылку к экшену в контроллере хоум*@
@Html.ActionLink("Link", "DataTransportByViewData")
@Html.CheckBox("CheckBox",true) @*1 параметр: имя 2 параметр: значение (true/false) тоесть стоит галочка или нет*@


<br />
@await Component.InvokeAsync("Simple")  @*<br /> ПЕРЕНОС СТРАНИЦЫ. await ПРОСТО ПИШЕМ (ПОЗЖЕ УЗНАЕМ).сюда надо передать наш вьюкомпонент (Название) чтоб вывести (2+2). Смотри папку ВЬЮ КОМПОНЕНТ*@

@*еще 2 метода :@**@

@*Вывод через наследование: См папку сепарэйтКомпонентс@**@

@await Component.InvokeAsync("SimpleComponentWithInheritance")

<br />
@*Вывод через Атрибут: См папку сепарэйтКомпонентс *@
<br />
@await Component.InvokeAsync("SimpleComponentWithAttribute")
<br />
@await Component.InvokeAsync("ViewExample") @*вьюкомпонент не пишем.  передали из папки хоум компонентс вьюэкземпл*@

Module17_ModelsAndViews/Views/Home/ViewWithSeparateLayout.cshtml
@model User[]

@{
    ViewBag.Title = "ViewWithSeparateLayout";
    Layout = "_TestLayout";
}

<ul>
    @foreach (var user in Model)
    {
        <li>@("Name: " + user.Name + " Age: " + user.Age + " City: " + user.City)</li>
    }
</ul>

Module17_ModelsAndViews/Views/Home/_PartialView.cshtml
@model string

<h2>
    It is Partial view: @Model @*ТУТ ВЫВЕДЕТСЯ ФИШ*@
</h2>
<h2>
     It is Partial view: @ViewBag.Partial @*ТУТ ВЫВЕДЕТСЯ ПАРШИАЛ*@ 
     @*В ОТДЕЛЬНЫЕ H2 ВЫВЕЛОСЬ ЧТОБ В ОДНУ СТРОКУ НЕ ЛИПЛО*@
</h2>

Module17_ModelsAndViews/Views/Home/_RenderPartialView.cshtml
<h2>
    It is Render Partial view
</h2>

Module17_ModelsAndViews/Views/Home/_ViewComponentsExample.cshtml
<p>
    @await Component.InvokeAsync("Simple")
</p>
<p>
    @await Component.InvokeAsync("SimpleComponentWithInheritance")
</p>
<p>
    @await Component.InvokeAsync("SimpleComponentWithAttribute")
</p>

Module17_ModelsAndViews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Module17_ModelsAndViews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Module17_ModelsAndViews</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="DataTransportByViewData">DataTransportByViewData</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="DataTransportByViewBag">DataTransportByViewBag</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="DataTransportByModel">DataTransportByModel</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ViewWithSeparateLayout">ViewWithSeparateLayout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Module17_ModelsAndViews
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

Module17_ModelsAndViews/Views/Shared/_TestLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @*<title>@ViewBag.Title</title>*@
</head>
<body>
    <div>
        @ViewBag.Title;
        Here Is Test Layout
        @RenderBody()
    </div>
</body>
</html>